CREATE DATABASE Platzi;

CREATE TABLE books (
	book_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	titulo VARCHAR (60) NOT NULL,
	autor VARCHAR (100) NOT NULL,
	publisher_id INTEGER  UNSIGNED NOT NULL,
	price DECIMAL (5,2)
);

CREATE TABLE publishers (
	publisher_id INTEGER UNSIGNED,
	name VARCHAR (100) NOT NULL,
	country VARCHAR (20)
);

CREATE TABLE users (
	user_id INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR (100) NOT NULL,
	email VARCHAR (100) NOT NULL UNIQUE
);